version: '1'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: krissisp/devops-for-programmers-project-74
    volumes:
      - ./app:/app
    command: npm run dev