version: '3.3'
services: 
  app:
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    build:
      context: .
      dockerfile: Dockerfile.production
    image: krissisp/devops-for-programmers-project-74
    command: npm run test
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres