version: '3.3'
services: 
  app:
  environment:
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    build:
      context: .
      dockerfile: Dockerfile.production
    image: krissisp/devops-for-programmers-project-74
    command: npm run test
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres